/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#00375e',
        'primary-container': '#1f4e79',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#a0cafc',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001d35',
        'on-primary-fixed-variant': '#184974',
        'on-primary-container': '#95bff1',
        'inverse-primary': '#a0cafc',
        'secondary': '#516072',
        'secondary-container': '#d1e1f7',
        'secondary-fixed': '#d4e4fa',
        'secondary-fixed-dim': '#b8c8de',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#0d1d2d',
        'on-secondary-fixed-variant': '#39485a',
        'on-secondary-container': '#556477',
        'tertiary': '#4c2e00',
        'tertiary-container': '#6a4300',
        'tertiary-fixed': '#ffddb5',
        'tertiary-fixed-dim': '#f5bc72',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#2a1800',
        'on-tertiary-fixed-variant': '#643f00',
        'on-tertiary-container': '#e9b268',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#35618d',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#42474f',
        'outline': '#72777f',
        'outline-variant': '#c2c7d0',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        editorial: '0 12px 32px -4px rgba(0, 55, 94, 0.08)',
        card: '0 4px 20px -4px rgba(0, 55, 94, 0.05)',
        'card-md': '0 4px 24px -4px rgba(0, 55, 94, 0.04)',
      },
    },
  },
  plugins: [],
}
